package org.fruitmc.mango.render.vulkan;

import org.lwjgl.vulkan.KHRPushDescriptor;
import org.lwjgl.vulkan.VK10;
import org.lwjgl.vulkan.VK13;

public final class MangoVulkanConstants {

    private MangoVulkanConstants() {
    }

    public static final int VK_SUCCESS = VK10.VK_SUCCESS;

    public static final int VK_BUFFER_USAGE_STORAGE_BUFFER_BIT = VK10.VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    public static final int VK_IMAGE_USAGE_STORAGE_BIT = VK10.VK_IMAGE_USAGE_STORAGE_BIT;

    public static final int VK_PIPELINE_BIND_POINT_COMPUTE = VK10.VK_PIPELINE_BIND_POINT_COMPUTE;
    public static final int VK_SHADER_STAGE_COMPUTE_BIT = VK10.VK_SHADER_STAGE_COMPUTE_BIT;

    public static final int VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = VK10.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    public static final int VK_DESCRIPTOR_TYPE_STORAGE_IMAGE = VK10.VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    public static final int VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER = VK10.VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER;
    public static final int VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER = VK10.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    public static final int VK_DESCRIPTOR_TYPE_STORAGE_BUFFER = VK10.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;

    public static final int VK_IMAGE_LAYOUT_GENERAL = VK10.VK_IMAGE_LAYOUT_GENERAL;
    public static final int VK_IMAGE_LAYOUT_UNDEFINED = VK10.VK_IMAGE_LAYOUT_UNDEFINED;
    public static final int VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = VK10.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    public static final int VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = VK10.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
    public static final int VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = VK10.VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;

    public static final int VK_IMAGE_ASPECT_COLOR_BIT = VK10.VK_IMAGE_ASPECT_COLOR_BIT;
    public static final int VK_IMAGE_ASPECT_DEPTH_BIT = VK10.VK_IMAGE_ASPECT_DEPTH_BIT;

    public static final int VK_QUEUE_FAMILY_IGNORED = VK10.VK_QUEUE_FAMILY_IGNORED;
    public static final long VK_WHOLE_SIZE = VK10.VK_WHOLE_SIZE;

    public static final long VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT = VK13.VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT;
    public static final long VK_PIPELINE_STAGE_2_HOST_BIT = VK13.VK_PIPELINE_STAGE_2_HOST_BIT;
    public static final long VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT = VK13.VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT;
    public static final long VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT = VK13.VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT;
    public static final long VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT = VK13.VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT;
    public static final long VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT = VK13.VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;
    public static final long VK_PIPELINE_STAGE_2_TRANSFER_BIT = VK13.VK_PIPELINE_STAGE_2_TRANSFER_BIT;
    public static final long VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT = VK13.VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT;
    public static final long VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT = VK13.VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT;

    public static final long VK_ACCESS_2_NONE = VK13.VK_ACCESS_2_NONE;
    public static final long VK_ACCESS_2_UNIFORM_READ_BIT = VK13.VK_ACCESS_2_UNIFORM_READ_BIT;
    public static final long VK_ACCESS_2_SHADER_READ_BIT = VK13.VK_ACCESS_2_SHADER_READ_BIT;
    public static final long VK_ACCESS_2_SHADER_WRITE_BIT = VK13.VK_ACCESS_2_SHADER_WRITE_BIT;
    public static final long VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT = VK13.VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT;
    public static final long VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT = VK13.VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT;
    public static final long VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT = VK13.VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT;
    public static final long VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = VK13.VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
    public static final long VK_ACCESS_2_TRANSFER_READ_BIT = VK13.VK_ACCESS_2_TRANSFER_READ_BIT;
    public static final long VK_ACCESS_2_TRANSFER_WRITE_BIT = VK13.VK_ACCESS_2_TRANSFER_WRITE_BIT;
    public static final long VK_ACCESS_2_HOST_WRITE_BIT = VK13.VK_ACCESS_2_HOST_WRITE_BIT;
    public static final long VK_ACCESS_2_HOST_READ_BIT = VK13.VK_ACCESS_2_HOST_READ_BIT;
    public static final long VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT = VK13.VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT;

    public static final int VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT =
        KHRPushDescriptor.VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR;
}